workspace:
  base: /go
  path: src/git.exlhub.io/exlinc/tools-mdlr

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -v
      - ./xplatform-build.bash
