workspace:
  base: /go
  path: src/github.com/exlinc/mdlr

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -v
      - go install
      - tools-mdlr import -f
      - ./xplatform-build.bash
