workspace:
  base: /go
  path: src/exlgit.com/tools/mdlr

pipeline:
  build:
    image: golang:1.9.2
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure -v
      - go install
      - tools-mdlr import -f
      - ./xplatform-build.bash
  git_push:
    image: appleboy/drone-git-push
    branch: master
    remote: https://exlgit.com/tools/mdlr-dist
    force: false
    commit: true
    path: 'build'
    commit_message: '[skip-ci] Push build'
    branches: [master]
